telefonicaid/lightweightm2m-iotagent

docs/deviceProvisioning.md
Change wrong IDs in the documentation.
=> FIX Minor problems in the code examples

docs/configurationProvisioning.md, docs/staticConfiguration.md
Fix some errors in the step by step guides.
=> FIX Errors in step-by-step guides

docs/userGuide.md
=> ADD Contribution guidelines

CHANGES_NEXT_RELEASE, rpm/create-rpm.sh
=> ADD New version of the create-rpm.sh script

README.md, mkdocs.yml
=> Add links to docs

CHANGES_NEXT_RELEASE, lib/services/lwm2mHandlers/updateRegistration.js, test/unit/registration-test.js, test/unit/update-registration-test.js
Fixes #109
- Correct handling of device update requests
- Unit test to check the new functionality
=> Fixes issue #109

CHANGES_NEXT_RELEASE, docker/Dockerfile
=> Update Node version

docker/Dockerfile, docker/README.md
LWM2M Equivalent of https://github.com/telefonicaid/iotagent-ul/pull/342
=> Expose Ports

config.js, docker/Dockerfile, docker/README.md, docker/entrypoint.sh, docker/hooks/build
Port over Docker Secrets support
see:  https://github.com/telefonicaid/iotagent-json/pull/390
=> Fix #159 - Add Docker Secrets

CHANGES_NEXT_RELEASE, package.json, test/unit/mongoDBUtils.js
This PR solves the short term task of https://github.com/telefonicaid/lightweightm2m-iotagent/blob/master/docs/roadmap.md
> Removal of warnings and deprecation warnings.
=> Fix: removes warnings 

CHANGES_NEXT_RELEASE, package.json, rpm/SPECS/iotagentLwm2m.spec
=> Step: 1.0.0-next -> 1.1.0

package.json
=> Step: 1.1.0 -> 1.1.0-next

.travis.yml, CHANGES_NEXT_RELEASE, README.md, docs/administrationGuide.md, docs/userGuide.md, package.json
Mimics PR https://github.com/telefonicaid/iotagent-json/pull/400
=> REMOVE node v6 ADD node v12

CHANGES_NEXT_RELEASE, package.json, rpm/SPECS/iotagentLwm2m.spec
Mimics PR https://github.com/telefonicaid/lightweightm2m-iotagent/pull/190
=> Step: 1.1.0-next -> 1.2.0

.jshintrc, CHANGES_NEXT_RELEASE, bin/lwm2mAgent.js, config.js, docker/README.md, docs/administrationGuide.md, docs/configurationProvisioning.md, docs/deprecated.md, docs/deviceProvisioning.md, docs/index.md, docs/limits.conf, docs/roadmap.md, docs/staticConfiguration.md, docs/sysctl.conf, docs/userGuide.md, package.json, test/.jshintrc
@fgalan
- Modify the LWM2M IoT Agent to deal with the option multi-thread.
- Add the corresponding new variable in the config.js (multiCore) with description.
Change in the Readme.md (Docker) and Administration Guide regarding High Performance execution of the LWM2M IoT Agent.
- Create 2 examples files of the user limits and sysctl configuration for high performance execution.
- Correct typos in all doc files.
- Correct wrong link to the image in Administration Guide document.
- Provide information of the LWM2M IoT Agent version in the request /iot/about.
- (Temporally) Update the package.json to link to the IoTAgent Node Lib with the changes. NEED TO BE REVERT when the [PR #815](https://github.com/telefonicaid/iotagent-node-lib/pull/815) is merged.
Unit tests, E2E tests in single-thread …
=> Update IoTA with the last changes of the IoTAgent Node Lib

CHANGES_NEXT_RELEASE, config.js, docker/Dockerfile, docker/README.md, docs/administrationGuide.md, docs/configurationProvisioning.md, docs/deviceProvisioning.md, docs/staticConfiguration.md, examples/config-factory.js
This contribution changes the configued non secure port 5684 to 5683 in order follow the standart definition. This contribution is releated with the issue #206
=> Changed non secure port 5684 port to 5683

.jshintrc, CHANGES_NEXT_RELEASE, bin/lwm2mAgent.js, config.js, docker/README.md, docs/administrationGuide.md, docs/configurationProvisioning.md, docs/deprecated.md, docs/deviceProvisioning.md, docs/index.md, docs/limits.conf, docs/roadmap.md, docs/staticConfiguration.md, docs/sysctl.conf, docs/userGuide.md, package.json, test/.jshintrc
Continues PR #203. The docker image for CI e2e will be built from this branch.
CC: @flopezag @jason-fox
=> Update IoTA with the last changes of the IoTAgent Node Lib (final landing)

CHANGES_NEXT_RELEASE, package.json, rpm/SPECS/iotagentLwm2m.spec
=> Step: 1.2.0-next -> 1.3.0

docs/roadmap.md
=> Roadmap update

CHANGES_NEXT_RELEASE, package.json, rpm/SPECS/iotagentLwm2m.spec
=> Step: 1.3.0-next -> 1.4.0

README.md, docs/administrationGuide.md, docs/userGuide.md
-  `http://www.omaspecworks.org/about-oma/work-program/m2m-enablers/` => `https://omaspecworks.org/what-is-oma-specworks/iot/`
-  `http://www.omaspecworks.org/iot/lightweight-m2m-lwm2m` => `https://omaspecworks.org/what-is-oma-specworks/iot/lightweight-m2m-lwm2m/`
=> OMA have updated their website. Fix Dead links

.github/workflows/ci.yml, package.json
The timeout to 3 seconds was missing from the coverage command
=> Fix coverage step

docs/contribution.md
Added contribution file to be aligned with CII Best Practices
=> Create contribution file

README.md
=> Updated README.md to add a link to contribution file and testing section

CHANGES_NEXT_RELEASE, lib/ngsiHandlers.js, lib/ngsiUtils.js, lib/services/lwm2mHandlers/commonLwm2m.js, lib/services/lwm2mHandlers/registration.js, package.json, test/unit/ngsiv2/active-attributes-test.js, test/unit/ngsiv2/commands-test.js, test/unit/ngsiv2/passive-attributes-test.js, test/unit/ngsiv2/registration-test.js
This PR has the aim to check if merging the changes have an impact on test passed on #251 
EDIT:
This PR replaces #251, so now it is intended for testing how this component unit tests behave when using jason-fox:feature/ngsi-v1 branch in the IOTA Lib.
=> NGSIv1 removal

.readthedocs.yml, docs/requirements.txt
mimics https://github.com/telefonicaid/iotagent-ul/pull/557
=> Update RTD files

CHANGES_NEXT_RELEASE, package.json, rpm/SPECS/iotagentLwm2m.spec
=> Step: 1.5.0-next -> 1.6.0

docs/requirements.txt
Align with https://github.com/telefonicaid/fiware-orion/blob/master/doc/requirements.txt
=> FIX requirements.txt
